# Dockerfile.base
FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir sentence-transformers

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    langchain langchain-huggingface chromadb
