# Dockerfile.api
FROM ai-base:latest

WORKDIR /app

# Копируем requirements и устанавливаем зависимости
COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Копируем исходный код
COPY schemas.py .
COPY database.py .
COPY main.py .

# Создаём директорию для SQLite
RUN mkdir -p /app/data
