{
 "title": "LLMOps Dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total LLM Prompts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "llm_prompts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LLM Generated Tokens Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "llm_tokens_generated_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LLM Generation Latency per Prompt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "llm_generation_latency_raw_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM Generation Latency per Prompt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llm_generation_latency_raw_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAG Empty Results Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rag_empty_results_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LLM Generation Latency [P95]",
   "type": "timeseries",
   "description": "How slow are my worst 5% of LLM requests over time?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(llm_generation_latency_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}